In [1]:
import pandas as pd
import numpy as np

In [2]:
pop_df = pd.read_csv(r"C:\Users\14802\Desktop\hate-crime analysis\working_notebooks\dataset_descriptions\state_population_by_year.csv", low_memory=False, index_col=False)

In [3]:
pop_df

               area  year  pop_estimate
0           Alabama  1991       4099156
1            Alaska  1991        570193
2           Arizona  1991       3788576
3          Arkansas  1991       2383144
4        California  1991      30470736
...             ...   ...           ...
1525       Virginia  2020       8632044
1526     Washington  2020       7718785
1527  West Virginia  2020       1789798
1528      Wisconsin  2020       5892323
1529        Wyoming  2020        577267

[1530 rows x 3 columns]

In [4]:
incidents_df = pd.read_csv(r"C:\Users\14802\Desktop\hate-crime analysis\working_notebooks\dataset_descriptions\totals_df.csv")

In [5]:
incidents_df

,data_year,state_name,bias_desc
0,1991,Arkansas,Anti-Black or African American
1,1991,Arkansas,Anti-White
2,1991,Arkansas,Anti-Black or African American
3,1991,Arkansas,Anti-White
4,1991,Arkansas,Anti-White
...,...,...,...
219572,2020,Wyoming,"Anti-Lesbian, Gay, Bisexual, or Transgender (M..."
219573,2020,Wyoming,Anti-White
219574,2020,Wyoming,Anti-White
219575,2020,Wyoming,Anti-Female
219576,2020,Wyoming,Anti-Gender Non-Conforming

In [6]:
incidents = pd.concat([incidents_df, incidents_df.bias_desc.str.get_dummies(sep=";")], axis=1)

In [7]:
incidents

,data_year,state_name,bias_desc,Anti-American Indian or Alaska Native,Anti-Arab,Anti-Asian,Anti-Atheism/Agnosticism,Anti-Bisexual,Anti-Black or African American,Anti-Buddhist,...,Anti-Native Hawaiian or Other Pacific Islander,Anti-Other Christian,Anti-Other Race/Ethnicity/Ancestry,Anti-Other Religion,Anti-Physical Disability,Anti-Protestant,Anti-Sikh,Anti-Transgender,Anti-White,Unknown (offender's motivation not known)
0,1991,Arkansas,Anti-Black or African American,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1991,Arkansas,Anti-White,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,1991,Arkansas,Anti-Black or African American,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1991,Arkansas,Anti-White,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,1991,Arkansas,Anti-White,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,2020,Wyoming,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219573,2020,Wyoming,Anti-White,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
219574,2020,Wyoming,Anti-White,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
219575,2020,Wyoming,Anti-Female,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219576,2020,Wyoming,Anti-Gender Non-Conforming,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
incidents['bias_grouping'] = incidents['bias_desc'].copy()

In [9]:
incidents['bias_grouping'].replace(['Anti-Gay (Male)', 'Anti-Lesbian (Female)', 'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)', 'Anti-Transgender', 'Anti-Bisexual', 'Anti-Gender Non-Conforming'], ['Anti-LGBTQ','Anti-LGBTQ','Anti-LGBTQ','Anti-LGBTQ','Anti-LGBTQ','Anti-LGBTQ'], inplace=True)

In [10]:
conditions = [
    (incidents['bias_grouping'] == "Anti-LGBTQ"),
    (incidents['bias_grouping'] != "Anti-LGBTQ")
]

values = [True, False]

incidents['anti_lgbtq_grouped'] = np.select(conditions,values)

In [11]:
incidents.drop(columns=["bias_grouping"], inplace=True)

In [12]:
incidents.insert(3, 'total_incidents', 1)

In [13]:
incidents

,data_year,state_name,bias_desc,total_incidents,Anti-American Indian or Alaska Native,Anti-Arab,Anti-Asian,Anti-Atheism/Agnosticism,Anti-Bisexual,Anti-Black or African American,...,Anti-Other Christian,Anti-Other Race/Ethnicity/Ancestry,Anti-Other Religion,Anti-Physical Disability,Anti-Protestant,Anti-Sikh,Anti-Transgender,Anti-White,Unknown (offender's motivation not known),anti_lgbtq_grouped
0,1991,Arkansas,Anti-Black or African American,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1991,Arkansas,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,1991,Arkansas,Anti-Black or African American,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1991,Arkansas,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1991,Arkansas,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,2020,Wyoming,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
219573,2020,Wyoming,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
219574,2020,Wyoming,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
219575,2020,Wyoming,Anti-Female,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219576,2020,Wyoming,Anti-Gender Non-Conforming,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [14]:
column_list = incidents.columns.tolist()

In [15]:
# code solution to change all to snake_case found here - https://stackoverflow.com/a/1176023

import re

snake_list = []

for column in column_list:
    column = re.sub(r'(?<!^)(?=[A-Z])', '_', column).lower()
    column = column.replace("(","")
    column = column.replace(")","")
    column = column.replace("'","")
    column = column.replace(",","")
    column = column.replace("-","")
    column = column.replace(" ", "_")
    column = column.replace("/", "")
    column = column.replace("__", "_")
        
    snake_list.append(column)

In [16]:
incidents.columns = snake_list

In [17]:
incidents

,data_year,state_name,bias_desc,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_offenders_motivation_not_known,anti_lgbtq_grouped
0,1991,Arkansas,Anti-Black or African American,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1991,Arkansas,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,1991,Arkansas,Anti-Black or African American,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1991,Arkansas,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1991,Arkansas,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,2020,Wyoming,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
219573,2020,Wyoming,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
219574,2020,Wyoming,Anti-White,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
219575,2020,Wyoming,Anti-Female,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219576,2020,Wyoming,Anti-Gender Non-Conforming,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [18]:
incidents = incidents.rename(columns={"data_year":"year", "state_name":"state","unknown_offenders_motivation_not_known":"unknown_motivation"})

In [19]:
incidents.drop(columns=["anti_lesbian_gay_bisexual_or_transgender_mixed_group"], inplace=True)

In [20]:
incidents.columns.tolist()

['year',
 'state',
 'bias_desc',
 'total_incidents',
 'anti_american_indian_or_alaska_native',
 'anti_arab',
 'anti_asian',
 'anti_atheism_agnosticism',
 'anti_bisexual',
 'anti_black_or_african_american',
 'anti_buddhist',
 'anti_catholic',
 'anti_eastern_orthodox_russian_greek_other',
 'anti_female',
 'anti_gay_male',
 'anti_gender_non_conforming',
 'anti_heterosexual',
 'anti_hindu',
 'anti_hispanic_or_latino',
 'anti_islamic_muslim',
 'anti_jehovahs_witness',
 'anti_jewish',
 'anti_lesbian_female',
 'anti_male',
 'anti_mental_disability',
 'anti_mormon',
 'anti_multiple_races_group',
 'anti_multiple_religions_group',
 'anti_native_hawaiian_or_other_pacific_islander',
 'anti_other_christian',
 'anti_other_race_ethnicity_ancestry',
 'anti_other_religion',
 'anti_physical_disability',
 'anti_protestant',
 'anti_sikh',
 'anti_transgender',
 'anti_white',
 'unknown_motivation',
 'anti_lgbtq_grouped']

In [21]:
incidents.to_csv('incidents_bias_matrix.csv', index=False)

In [22]:
totals_1991 = incidents.query('year == 1991').groupby("state").sum()

In [23]:
totals_1991.drop(columns=["year"], inplace=True)

In [24]:
totals_1991.insert(0, 'year', 1991)

In [25]:
totals_1991.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Arizona,1991,48,0,2,2,0,0,23,0,1,...,0,0,1,0,5,0,0,4,0,1
Arkansas,1991,12,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,9,0,0
California,1991,5,0,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
Colorado,1991,128,0,2,8,0,0,50,0,1,...,0,2,0,0,2,0,0,22,0,10
Connecticut,1991,69,0,2,1,0,0,27,0,1,...,0,0,0,0,0,0,0,11,0,12

In [26]:
totals_1992 = incidents.query('year == 1992').groupby('state').sum()
totals_1992.drop(columns=["year"], inplace=True)
totals_1992.insert(0, 'year', 1992)
totals_1992.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,1992,4,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,1,0,0
Arizona,1992,172,3,2,8,0,0,69,0,0,...,0,3,1,0,0,0,0,22,0,31
Arkansas,1992,38,0,0,0,0,0,9,0,0,...,0,0,0,0,0,0,0,23,0,5
California,1992,77,0,1,11,0,0,14,0,0,...,0,4,2,0,0,0,0,12,0,26
Colorado,1992,261,1,3,13,0,0,103,0,0,...,0,10,1,0,1,0,0,35,0,29

In [27]:
totals_1993 = incidents.query('year == 1993').groupby('state').sum()
totals_1993.drop(columns=["year"], inplace=True)
totals_1993.insert(0, 'year', 1993)
totals_1993.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,1993,5,0,0,0,0,0,4,0,0,...,0,0,0,0,0,0,0,1,0,0
Alaska,1993,24,0,0,2,0,0,11,0,0,...,0,1,0,0,0,0,0,4,0,5
Arizona,1993,208,1,1,9,0,0,87,0,1,...,0,8,4,0,1,0,0,34,0,13
Arkansas,1993,13,1,0,0,0,0,4,0,0,...,0,0,0,0,0,0,0,6,0,2
California,1993,364,0,1,36,0,0,72,0,0,...,0,8,1,0,1,0,0,73,0,116

In [28]:
totals_1994 = incidents.query('year == 1994').groupby('state').sum()
totals_1994.drop(columns=["year"], inplace=True)
totals_1994.insert(0, 'year', 1994)
totals_1994.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,1994,9,2,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,4,0,0
Arizona,1994,205,1,5,6,0,0,72,0,3,...,0,2,8,0,1,0,0,23,0,30
Arkansas,1994,10,0,0,2,0,0,4,0,0,...,0,0,0,0,1,0,0,2,0,1
California,1994,354,0,0,33,0,0,74,0,0,...,0,16,6,0,3,0,0,63,0,95
Colorado,1994,174,1,4,6,0,1,51,0,3,...,0,7,0,0,1,0,0,28,0,23

In [29]:
totals_1995 = incidents.query('year == 1995').groupby('state').sum()
totals_1995.drop(columns=["year"], inplace=True)
totals_1995.insert(0, 'year', 1995)
totals_1995.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,1995,8,1,0,1,0,0,3,0,0,...,0,0,0,0,0,0,0,1,0,1
Arizona,1995,220,1,4,9,0,0,89,0,3,...,0,3,2,0,1,0,0,27,0,39
Arkansas,1995,7,0,0,1,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,0
California,1995,1751,1,0,142,0,1,568,0,4,...,0,73,18,0,8,0,0,195,0,315
Colorado,1995,149,2,7,15,0,1,46,0,1,...,0,6,1,0,1,0,0,13,0,14

In [30]:
totals_1996 = incidents.query('year == 1996').groupby('state').sum()
totals_1996.drop(columns=["year"], inplace=True)
totals_1996.insert(0, 'year', 1996)
totals_1996.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,1996,9,1,0,0,0,0,5,0,0,...,0,1,0,0,0,0,0,0,0,2
Arizona,1996,250,2,2,5,0,0,109,0,0,...,0,4,4,0,1,0,0,22,0,35
Arkansas,1996,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
California,1996,2052,5,0,153,0,3,759,0,5,...,0,90,11,0,33,0,0,220,0,361
Colorado,1996,133,1,0,4,0,0,72,0,0,...,0,7,1,0,4,0,0,14,0,9

In [31]:
totals_1997 = incidents.query('year == 1997').groupby('state').sum()
totals_1997.drop(columns=["year"], inplace=True)
totals_1997.insert(0, 'year', 1997)
totals_1997.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,1997,10,0,0,1,0,0,5,0,1,...,0,0,0,0,1,0,0,0,0,1
Arizona,1997,330,3,2,8,0,0,123,0,2,...,0,4,6,0,4,0,0,38,0,55
California,1997,1831,2,0,160,1,0,630,0,0,...,0,78,6,2,21,0,0,147,0,355
Colorado,1997,115,1,0,6,0,1,35,0,1,...,0,4,1,0,0,0,0,16,0,14
Connecticut,1997,113,1,0,1,0,0,47,0,0,...,0,6,1,2,0,0,0,21,0,3

In [32]:
totals_1998 = incidents.query('year == 1998').groupby('state').sum()
totals_1998.drop(columns=["year"], inplace=True)
totals_1998.insert(0, 'year', 1998)
totals_1998.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Arizona,1998,283,4,0,6,0,0,103,0,2,...,0,4,7,1,3,0,0,13,0,56
Arkansas,1998,3,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,1
California,1998,1749,5,0,135,0,0,509,0,13,...,0,72,17,3,14,0,0,147,0,386
Colorado,1998,131,0,1,3,0,1,52,0,1,...,0,3,1,0,2,0,0,19,0,17
Connecticut,1998,111,0,0,4,0,0,51,0,1,...,0,6,1,1,1,0,0,7,0,14

In [33]:
totals_1999 = incidents.query('year == 1999').groupby('state').sum()
totals_1999.drop(columns=["year"], inplace=True)
totals_1999.insert(0, 'year', 1999)
totals_1999.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,1999,5,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,1,0,0
Arizona,1999,252,1,2,10,0,0,93,0,2,...,0,8,7,0,0,0,0,11,0,43
Arkansas,1999,8,0,0,0,0,0,5,0,0,...,0,1,0,0,0,0,0,1,0,0
California,1999,1949,5,0,126,0,0,600,0,8,...,0,82,27,2,15,0,0,127,0,436
Colorado,1999,155,1,1,7,0,0,60,0,3,...,0,7,1,2,1,0,0,11,0,26

In [34]:
totals_2000 = incidents.query('year == 2000').groupby('state').sum()
totals_2000.drop(columns=["year"], inplace=True)
totals_2000.insert(0, 'year', 2000)
totals_2000.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,2000,4,0,0,0,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,0
Arizona,2000,281,5,3,5,0,0,91,0,3,...,0,2,5,1,0,0,0,15,0,54
Arkansas,2000,3,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
California,2000,1943,2,0,100,0,1,606,0,9,...,0,96,30,3,18,0,0,145,0,399
Colorado,2000,101,1,4,9,0,0,35,0,2,...,0,5,0,0,0,0,0,6,0,15

In [35]:
totals_2001 = incidents.query('year == 2001').groupby('state').sum()
totals_2001.drop(columns=["year"], inplace=True)
totals_2001.insert(0, 'year', 2001)
totals_2001.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,2001,20,12,0,0,0,0,3,0,0,...,0,1,0,0,0,0,0,1,0,1
Arizona,2001,386,5,0,5,0,0,112,0,1,...,0,78,8,0,2,0,0,13,0,42
Arkansas,2001,3,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
California,2001,2246,4,0,93,1,2,596,0,9,...,0,428,19,4,4,0,0,128,0,420
Colorado,2001,126,1,1,5,0,0,30,0,1,...,0,13,0,0,0,0,0,6,0,17

In [36]:
totals_2002 = incidents.query('year == 2002').groupby('state').sum()
totals_2002.drop(columns=["year"], inplace=True)
totals_2002.insert(0, 'year', 2002)
totals_2002.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2002,2,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
Alaska,2002,7,2,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,3
Arizona,2002,241,3,0,9,0,0,69,0,5,...,0,20,6,1,1,0,0,11,0,51
California,2002,1648,3,4,70,0,0,482,0,8,...,0,195,26,3,6,0,0,91,0,364
Colorado,2002,96,0,0,7,0,0,37,0,0,...,0,4,1,0,0,0,0,7,0,12

In [37]:
totals_2003 = incidents.query('year == 2003').groupby('state').sum()
totals_2003.drop(columns=["year"], inplace=True)
totals_2003.insert(0, 'year', 2003)
totals_2003.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2003,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Alaska,2003,13,6,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,1,0,3
Arizona,2003,247,3,0,0,1,0,68,0,6,...,0,32,8,3,0,0,0,7,0,37
Arkansas,2003,173,3,0,0,0,0,46,0,0,...,0,1,1,1,0,0,0,96,0,6
California,2003,1472,2,0,66,0,1,463,0,10,...,0,161,27,1,7,0,0,85,0,337

In [38]:
totals_2004 = incidents.query('year == 2004').groupby('state').sum()
totals_2004.drop(columns=["year"], inplace=True)
totals_2004.insert(0, 'year', 2004)
totals_2004.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2004,3,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
Alaska,2004,9,1,0,1,0,0,6,0,0,...,0,0,0,0,0,0,0,0,0,0
Arizona,2004,225,2,0,5,0,0,73,0,0,...,0,21,2,1,1,0,0,11,0,33
Arkansas,2004,83,3,0,2,0,0,28,0,0,...,0,1,1,0,0,0,0,40,0,1
California,2004,1393,3,0,69,0,1,500,0,9,...,0,105,19,2,3,0,0,61,0,263

In [39]:
totals_2005 = incidents.query('year == 2005').groupby('state').sum()
totals_2005.drop(columns=["year"], inplace=True)
totals_2005.insert(0, 'year', 2005)
totals_2005.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,2005,4,2,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
Arizona,2005,194,2,0,4,0,0,66,0,0,...,0,10,4,0,2,0,0,13,0,35
Arkansas,2005,135,7,0,5,1,8,39,0,2,...,0,1,0,0,3,0,0,42,0,15
California,2005,1380,2,0,50,1,4,490,0,10,...,0,89,26,3,10,0,0,77,0,254
Colorado,2005,125,1,0,6,0,0,41,0,1,...,0,5,4,0,1,0,0,8,0,16

In [40]:
totals_2006 = incidents.query('year == 2006').groupby('state').sum()
totals_2006.drop(columns=["year"], inplace=True)
totals_2006.insert(0, 'year', 2006)
totals_2006.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,2006,6,1,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,2
Arizona,2006,169,3,0,2,0,0,46,0,0,...,0,13,4,0,3,0,0,6,0,29
Arkansas,2006,113,0,0,3,0,6,36,0,0,...,0,0,1,0,1,0,0,47,0,11
California,2006,1297,4,0,52,1,3,432,0,11,...,0,94,22,1,13,0,0,64,0,246
Colorado,2006,140,0,0,1,0,0,35,0,2,...,0,4,6,1,5,0,0,15,0,16

In [41]:
totals_2007 = incidents.query('year == 2007').groupby('state').sum()
totals_2007.drop(columns=["year"], inplace=True)
totals_2007.insert(0, 'year', 2007)
totals_2007.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2007,7,0,0,1,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,1
Alaska,2007,8,0,0,0,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,2
Arizona,2007,161,1,0,5,0,0,57,0,0,...,0,11,4,1,0,0,0,6,0,27
Arkansas,2007,33,1,0,3,0,0,14,0,0,...,0,0,0,0,0,0,0,3,0,8
California,2007,1400,1,0,54,2,2,496,0,10,...,0,96,24,2,11,0,0,73,0,261

In [42]:
totals_2008 = incidents.query('year == 2008').groupby('state').sum()
totals_2008.drop(columns=["year"], inplace=True)
totals_2008.insert(0, 'year', 2008)
totals_2008.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2008,11,0,0,0,0,0,5,0,0,...,0,0,1,0,0,0,0,1,0,2
Alaska,2008,8,0,0,1,0,0,2,0,0,...,0,0,1,0,0,0,0,1,0,1
Arizona,2008,185,4,0,3,0,0,55,0,2,...,0,10,5,0,1,0,0,8,0,25
Arkansas,2008,92,0,0,0,0,1,41,0,0,...,0,0,2,0,1,0,0,25,0,11
California,2008,1382,1,0,37,1,2,457,0,12,...,0,69,63,2,8,0,0,42,0,281

In [43]:
totals_2009 = incidents.query('year == 2009').groupby('state').sum()
totals_2009.drop(columns=["year"], inplace=True)
totals_2009.insert(0, 'year', 2009)
totals_2009.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2009,9,0,0,0,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,2
Alaska,2009,9,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
Arizona,2009,219,2,0,8,0,0,59,0,1,...,0,7,7,0,1,0,0,5,0,41
Arkansas,2009,75,1,0,1,1,4,23,0,1,...,0,0,0,0,1,0,0,20,0,13
California,2009,1018,2,0,25,0,1,358,0,9,...,0,65,21,2,3,0,0,37,0,222

In [44]:
totals_2010 = incidents.query('year == 2010').groupby('state').sum()
totals_2010.drop(columns=["year"], inplace=True)
totals_2010.insert(0, 'year', 2010)
totals_2010.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2010,19,0,0,0,0,0,11,0,0,...,0,2,1,0,0,0,0,1,0,2
Alaska,2010,7,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,2,0,1
Arizona,2010,236,1,0,6,0,0,80,0,0,...,0,12,8,2,1,0,0,7,0,51
Arkansas,2010,64,1,0,5,0,3,21,0,2,...,0,2,1,0,0,0,0,11,0,9
California,2010,1092,0,0,32,0,3,323,0,10,...,0,57,25,3,6,0,0,47,0,274

In [45]:
totals_2011 = incidents.query('year == 2011').groupby('state').sum()
totals_2011.drop(columns=["year"], inplace=True)
totals_2011.insert(0, 'year', 2011)
totals_2011.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2011,83,1,0,1,0,0,31,0,0,...,0,3,0,0,0,0,0,20,0,6
Alaska,2011,8,2,0,0,0,0,2,0,0,...,0,0,0,0,1,0,0,1,0,1
Arizona,2011,193,2,0,7,0,0,59,0,0,...,0,9,6,0,1,0,0,11,0,35
Arkansas,2011,36,2,0,0,0,0,15,0,0,...,0,1,1,0,2,0,0,9,0,2
California,2011,1040,1,0,30,0,3,312,0,6,...,0,83,38,3,1,0,0,36,0,242

In [46]:
totals_2012 = incidents.query('year == 2012').groupby('state').sum()
totals_2012.drop(columns=["year"], inplace=True)
totals_2012.insert(0, 'year', 2012)
totals_2012.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2012,6,0,0,0,0,0,3,0,0,...,0,0,1,0,0,0,0,0,0,0
Alaska,2012,6,1,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,1,0,0
Arizona,2012,176,2,0,3,0,1,56,0,3,...,0,7,4,0,0,0,0,9,0,43
Arkansas,2012,51,0,0,0,0,6,10,0,1,...,0,0,1,0,0,0,0,9,0,14
California,2012,910,3,0,24,1,2,290,0,7,...,0,63,20,0,2,0,0,40,0,233

In [47]:
totals_2013 = incidents.query('year == 2013').groupby('state').sum()
totals_2013.drop(columns=["year"], inplace=True)
totals_2013.insert(0, 'year', 2013)
totals_2013.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2013,6,0,0,0,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,1
Alaska,2013,8,3,0,0,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,0
Arizona,2013,201,0,0,1,0,1,68,0,1,...,0,14,5,2,1,0,0,15,0,36
Arkansas,2013,27,0,0,0,0,0,14,0,0,...,0,0,0,0,0,0,0,3,0,8
California,2013,842,3,0,30,0,4,286,0,7,...,0,51,23,0,3,0,6,38,0,219

In [48]:
totals_2014 = incidents.query('year == 2014').groupby('state').sum()
totals_2014.drop(columns=["year"], inplace=True)
totals_2014.insert(0, 'year', 2014)
totals_2014.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2014,9,1,0,1,0,0,3,0,0,...,0,0,0,0,0,0,0,2,0,0
Alaska,2014,6,3,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,1
Arizona,2014,265,5,0,6,0,2,93,0,2,...,0,19,6,1,2,0,0,15,0,55
Arkansas,2014,11,0,0,0,0,0,4,0,1,...,0,1,0,0,0,0,0,3,0,1
California,2014,759,3,0,19,0,2,242,0,5,...,0,51,20,2,2,0,22,28,0,208

In [49]:
totals_2015 = incidents.query('year == 2015').groupby('state').sum()
totals_2015.drop(columns=["year"], inplace=True)
totals_2015.insert(0, 'year', 2015)
totals_2015.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2015,10,0,0,0,0,0,7,0,0,...,0,0,0,0,0,0,0,1,0,2
Alaska,2015,8,0,1,0,0,0,4,0,0,...,0,0,0,0,0,0,0,2,0,1
Arizona,2015,276,6,0,3,0,0,97,0,1,...,0,5,7,3,1,0,0,29,0,57
Arkansas,2015,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
California,2015,837,2,10,19,1,4,230,1,11,...,0,33,26,4,3,0,24,34,0,211

In [50]:
totals_2016 = incidents.query('year == 2016').groupby('state').sum()
totals_2016.drop(columns=["year"], inplace=True)
totals_2016.insert(0, 'year', 2016)
totals_2016.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2016,14,1,0,0,0,0,8,0,0,...,0,0,0,0,0,0,0,1,0,1
Alaska,2016,11,2,0,1,0,0,6,0,0,...,0,0,0,0,0,0,0,2,0,0
Arizona,2016,217,1,0,3,0,3,59,0,0,...,0,5,6,1,0,0,0,20,0,52
Arkansas,2016,12,0,0,0,0,0,3,0,0,...,0,2,0,0,0,0,1,0,0,1
California,2016,931,9,19,23,0,1,251,0,12,...,15,40,14,2,2,1,25,58,0,230

In [51]:
totals_2017 = incidents.query('year == 2017').groupby('state').sum()
totals_2017.drop(columns=["year"], inplace=True)
totals_2017.insert(0, 'year', 2017)
totals_2017.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2017,14,0,0,0,0,0,7,0,0,...,0,0,0,0,0,0,0,4,0,0
Alaska,2017,4,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,2,0,0
Arizona,2017,264,3,0,2,0,2,86,0,1,...,0,3,4,4,0,0,12,30,0,52
Arkansas,2017,24,0,0,0,0,0,14,0,0,...,0,0,0,0,0,0,0,5,0,3
California,2017,1094,5,15,37,0,3,303,1,20,...,4,45,12,2,7,5,27,47,0,270

In [52]:
totals_2018 = incidents.query('year == 2018').groupby('state').sum()
totals_2018.drop(columns=["year"], inplace=True)
totals_2018.insert(0, 'year', 2018)
totals_2018.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alaska,2018,5,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,2,0,0
Arizona,2018,169,0,0,1,0,1,59,0,2,...,0,2,0,1,1,0,3,14,0,41
Arkansas,2018,22,0,0,0,0,0,9,0,0,...,0,1,0,0,0,0,0,6,0,2
California,2018,1065,2,16,34,1,3,277,0,10,...,6,43,17,3,1,0,19,48,0,257
Colorado,2018,97,1,2,2,1,0,24,0,0,...,0,3,1,2,0,0,3,5,0,23

In [53]:
totals_2019 = incidents.query('year == 2019').groupby('state').sum()
totals_2019.drop(columns=["year"], inplace=True)
totals_2019.insert(0, 'year', 2019)
totals_2019.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2019,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Alaska,2019,11,2,0,0,0,0,4,0,0,...,0,1,0,0,0,0,0,0,0,4
Arizona,2019,209,4,0,1,0,1,98,0,0,...,1,3,3,1,0,0,3,15,0,31
Arkansas,2019,14,0,0,1,0,0,8,0,0,...,0,0,0,0,0,0,0,1,0,3
California,2019,1015,1,20,43,0,3,243,0,7,...,6,41,14,6,1,0,30,39,0,264

In [54]:
totals_2020 = incidents.query('year == 2020').groupby('state').sum()
totals_2020.drop(columns=["year"], inplace=True)
totals_2020.insert(0, 'year', 2020)
totals_2020.head()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Alabama,2020,27,0,0,0,0,0,7,0,0,...,1,0,0,0,0,1,0,14,0,1
Alaska,2020,10,1,0,0,0,0,2,0,0,...,1,0,0,0,0,0,1,1,0,2
Arizona,2020,282,8,1,4,0,0,118,0,0,...,4,5,5,2,4,2,6,29,0,40
Arkansas,2020,50,1,0,1,0,0,11,0,2,...,0,2,1,0,0,1,1,11,0,10
California,2020,1339,2,10,91,0,4,460,6,6,...,6,59,17,4,3,4,54,82,0,268

In [55]:
totals_2020.tail()

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Virginia,2020,187,0,2,5,0,0,70,0,0,...,1,10,2,0,1,0,2,29,0,25
Washington,2020,451,10,5,26,1,0,159,0,6,...,5,21,0,4,2,4,20,47,0,80
West Virginia,2020,82,5,1,0,2,0,11,0,1,...,0,0,3,1,0,14,0,20,0,4
Wisconsin,2020,157,3,1,3,0,0,35,1,0,...,1,5,1,0,0,6,2,50,0,16
Wyoming,2020,18,0,0,0,0,0,6,0,0,...,0,0,1,0,0,0,0,2,0,3

In [56]:
incidents_by_state_by_year = pd.concat([totals_1991, totals_1992, totals_1993, totals_1994, totals_1995, totals_1996, totals_1997, totals_1998 ,totals_1999, totals_2000, totals_2001, totals_2002, totals_2003, totals_2004, totals_2005, totals_2006, totals_2007, totals_2008, totals_2009, totals_2010, totals_2011, totals_2012, totals_2013, totals_2014, totals_2015, totals_2016, totals_2017, totals_2018, totals_2019, totals_2020], axis=0)

In [57]:
incidents_by_state_by_year

,year,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,anti_buddhist,anti_catholic,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
state,,,,,,,,,,,,,,,,,,,,,
Arizona,1991,48,0,2,2,0,0,23,0,1,...,0,0,1,0,5,0,0,4,0,1
Arkansas,1991,12,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,9,0,0
California,1991,5,0,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
Colorado,1991,128,0,2,8,0,0,50,0,1,...,0,2,0,0,2,0,0,22,0,10
Connecticut,1991,69,0,2,1,0,0,27,0,1,...,0,0,0,0,0,0,0,11,0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginia,2020,187,0,2,5,0,0,70,0,0,...,1,10,2,0,1,0,2,29,0,25
Washington,2020,451,10,5,26,1,0,159,0,6,...,5,21,0,4,2,4,20,47,0,80
West Virginia,2020,82,5,1,0,2,0,11,0,1,...,0,0,3,1,0,14,0,20,0,4
Wisconsin,2020,157,3,1,3,0,0,35,1,0,...,1,5,1,0,0,6,2,50,0,16
Wyoming,2020,18,0,0,0,0,0,6,0,0,...,0,0,1,0,0,0,0,2,0,3

In [58]:
incidents_by_state_by_year.to_csv('incidents_year_and_state.csv')

In [59]:
pop_df

               area  year  pop_estimate
0           Alabama  1991       4099156
1            Alaska  1991        570193
2           Arizona  1991       3788576
3          Arkansas  1991       2383144
4        California  1991      30470736
...             ...   ...           ...
1525       Virginia  2020       8632044
1526     Washington  2020       7718785
1527  West Virginia  2020       1789798
1528      Wisconsin  2020       5892323
1529        Wyoming  2020        577267

[1530 rows x 3 columns]

In [60]:
pop_df.set_axis(['state', 'year', 'population_estimate'], axis=1, inplace=True)

In [61]:
merged_df = pd.merge(pop_df, incidents_by_state_by_year, how='left', on=['state', 'year'])

In [62]:
merged_df

,state,year,population_estimate,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
0,Alabama,1991,4099156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,1991,570193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arizona,1991,3788576,48.0,0.0,2.0,2.0,0.0,0.0,23.0,...,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,0.0,1.0
3,Arkansas,1991,2383144,12.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0
4,California,1991,30470736,5.0,0.0,0.0,1.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Virginia,2020,8632044,187.0,0.0,2.0,5.0,0.0,0.0,70.0,...,1.0,10.0,2.0,0.0,1.0,0.0,2.0,29.0,0.0,25.0
1526,Washington,2020,7718785,451.0,10.0,5.0,26.0,1.0,0.0,159.0,...,5.0,21.0,0.0,4.0,2.0,4.0,20.0,47.0,0.0,80.0
1527,West Virginia,2020,1789798,82.0,5.0,1.0,0.0,2.0,0.0,11.0,...,0.0,0.0,3.0,1.0,0.0,14.0,0.0,20.0,0.0,4.0
1528,Wisconsin,2020,5892323,157.0,3.0,1.0,3.0,0.0,0.0,35.0,...,1.0,5.0,1.0,0.0,0.0,6.0,2.0,50.0,0.0,16.0
1529,Wyoming,2020,577267,18.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0

In [63]:
merged_df['year'] = merged_df.year.astype(str)

In [64]:
merged_df.head()

,state,year,population_estimate,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
0,Alabama,1991,4099156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,1991,570193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arizona,1991,3788576,48.0,0.0,2.0,2.0,0.0,0.0,23.0,...,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,0.0,1.0
3,Arkansas,1991,2383144,12.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0
4,California,1991,30470736,5.0,0.0,0.0,1.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1530 entries, 0 to 1529
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   state                                           1530 non-null   object
 1   year                                            1530 non-null   object
 2   population_estimate                             1530 non-null   int64
 3   total_incidents                                 1434 non-null   float64
 4   anti_american_indian_or_alaska_native           1434 non-null   float64
 5   anti_arab                                       1434 non-null   float64
 6   anti_asian                                      1434 non-null   float64
 7   anti_atheism_agnosticism                        1434 non-null   float64
 8   anti_bisexual                                   1434 non-null   float64
 9   anti_black_or_african_american                  1434 non-null   float64
 10  anti_buddhist                                   1434 non-null   float64
 11  anti_catholic                                   1434 non-null   float64
 12  anti_eastern_orthodox_russian_greek_other       1434 non-null   float64
 13  anti_female                                     1434 non-null   float64
 14  anti_gay_male                                   1434 non-null   float64
 15  anti_gender_non_conforming                      1434 non-null   float64
 16  anti_heterosexual                               1434 non-null   float64
 17  anti_hindu                                      1434 non-null   float64
 18  anti_hispanic_or_latino                         1434 non-null   float64
 19  anti_islamic_muslim                             1434 non-null   float64
 20  anti_jehovahs_witness                           1434 non-null   float64
 21  anti_jewish                                     1434 non-null   float64
 22  anti_lesbian_female                             1434 non-null   float64
 23  anti_male                                       1434 non-null   float64
 24  anti_mental_disability                          1434 non-null   float64
 25  anti_mormon                                     1434 non-null   float64
 26  anti_multiple_races_group                       1434 non-null   float64
 27  anti_multiple_religions_group                   1434 non-null   float64
 28  anti_native_hawaiian_or_other_pacific_islander  1434 non-null   float64
 29  anti_other_christian                            1434 non-null   float64
 30  anti_other_race_ethnicity_ancestry              1434 non-null   float64
 31  anti_other_religion                             1434 non-null   float64
 32  anti_physical_disability                        1434 non-null   float64
 33  anti_protestant                                 1434 non-null   float64
 34  anti_sikh                                       1434 non-null   float64
 35  anti_transgender                                1434 non-null   float64
 36  anti_white                                      1434 non-null   float64
 37  unknown_motivation                              1434 non-null   float64
 38  anti_lgbtq_grouped                              1434 non-null   float64
dtypes: float64(36), int64(1), object(2)
memory usage: 478.1+ KB

In [66]:
grouped_df = merged_df.copy()

In [67]:
grouped_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1530 entries, 0 to 1529
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   state                                           1530 non-null   object
 1   year                                            1530 non-null   object
 2   population_estimate                             1530 non-null   int64
 3   total_incidents                                 1434 non-null   float64
 4   anti_american_indian_or_alaska_native           1434 non-null   float64
 5   anti_arab                                       1434 non-null   float64
 6   anti_asian                                      1434 non-null   float64
 7   anti_atheism_agnosticism                        1434 non-null   float64
 8   anti_bisexual                                   1434 non-null   float64
 9   anti_black_or_african_american                  1434 non-null   float64
 10  anti_buddhist                                   1434 non-null   float64
 11  anti_catholic                                   1434 non-null   float64
 12  anti_eastern_orthodox_russian_greek_other       1434 non-null   float64
 13  anti_female                                     1434 non-null   float64
 14  anti_gay_male                                   1434 non-null   float64
 15  anti_gender_non_conforming                      1434 non-null   float64
 16  anti_heterosexual                               1434 non-null   float64
 17  anti_hindu                                      1434 non-null   float64
 18  anti_hispanic_or_latino                         1434 non-null   float64
 19  anti_islamic_muslim                             1434 non-null   float64
 20  anti_jehovahs_witness                           1434 non-null   float64
 21  anti_jewish                                     1434 non-null   float64
 22  anti_lesbian_female                             1434 non-null   float64
 23  anti_male                                       1434 non-null   float64
 24  anti_mental_disability                          1434 non-null   float64
 25  anti_mormon                                     1434 non-null   float64
 26  anti_multiple_races_group                       1434 non-null   float64
 27  anti_multiple_religions_group                   1434 non-null   float64
 28  anti_native_hawaiian_or_other_pacific_islander  1434 non-null   float64
 29  anti_other_christian                            1434 non-null   float64
 30  anti_other_race_ethnicity_ancestry              1434 non-null   float64
 31  anti_other_religion                             1434 non-null   float64
 32  anti_physical_disability                        1434 non-null   float64
 33  anti_protestant                                 1434 non-null   float64
 34  anti_sikh                                       1434 non-null   float64
 35  anti_transgender                                1434 non-null   float64
 36  anti_white                                      1434 non-null   float64
 37  unknown_motivation                              1434 non-null   float64
 38  anti_lgbtq_grouped                              1434 non-null   float64
dtypes: float64(36), int64(1), object(2)
memory usage: 478.1+ KB

In [68]:
grouped_df

,state,year,population_estimate,total_incidents,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,anti_black_or_african_american,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
0,Alabama,1991,4099156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,1991,570193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arizona,1991,3788576,48.0,0.0,2.0,2.0,0.0,0.0,23.0,...,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,0.0,1.0
3,Arkansas,1991,2383144,12.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0
4,California,1991,30470736,5.0,0.0,0.0,1.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Virginia,2020,8632044,187.0,0.0,2.0,5.0,0.0,0.0,70.0,...,1.0,10.0,2.0,0.0,1.0,0.0,2.0,29.0,0.0,25.0
1526,Washington,2020,7718785,451.0,10.0,5.0,26.0,1.0,0.0,159.0,...,5.0,21.0,0.0,4.0,2.0,4.0,20.0,47.0,0.0,80.0
1527,West Virginia,2020,1789798,82.0,5.0,1.0,0.0,2.0,0.0,11.0,...,0.0,0.0,3.0,1.0,0.0,14.0,0.0,20.0,0.0,4.0
1528,Wisconsin,2020,5892323,157.0,3.0,1.0,3.0,0.0,0.0,35.0,...,1.0,5.0,1.0,0.0,0.0,6.0,2.0,50.0,0.0,16.0
1529,Wyoming,2020,577267,18.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0

In [69]:
per_capita = grouped_df.copy()

In [70]:
per_capita.dropna(inplace=True)

In [72]:
pop_list = per_capita.population_estimate.tolist()

In [73]:
total_incidents_list = per_capita.total_incidents.tolist()

In [91]:
per_capita_list = []

def per_capita_func():
    for pop, total in zip(pop_list, total_incidents_list):

        per_capita_list.append((total/pop)*100000)

In [92]:
per_capita_func()

In [95]:
per_capita.insert(4, 'total_incidents_per_capita', per_capita_list)

In [97]:
per_capita.reset_index(inplace=True)
per_capita.drop(columns=["index"], inplace=True)
per_capita

,state,year,population_estimate,total_incidents,total_incidents_per_capita,anti_american_indian_or_alaska_native,anti_arab,anti_asian,anti_atheism_agnosticism,anti_bisexual,...,anti_other_christian,anti_other_race_ethnicity_ancestry,anti_other_religion,anti_physical_disability,anti_protestant,anti_sikh,anti_transgender,anti_white,unknown_motivation,anti_lgbtq_grouped
0,Arizona,1991,3788576,48.0,1.266967,0.0,2.0,2.0,0.0,0.0,...,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,0.0,1.0
1,Arkansas,1991,2383144,12.0,0.503537,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0
2,California,1991,30470736,5.0,0.016409,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Colorado,1991,3387119,128.0,3.779023,0.0,2.0,8.0,0.0,0.0,...,0.0,2.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,10.0
4,Connecticut,1991,3302895,69.0,2.089076,0.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,Virginia,2020,8632044,187.0,2.166347,0.0,2.0,5.0,0.0,0.0,...,1.0,10.0,2.0,0.0,1.0,0.0,2.0,29.0,0.0,25.0
1430,Washington,2020,7718785,451.0,5.842888,10.0,5.0,26.0,1.0,0.0,...,5.0,21.0,0.0,4.0,2.0,4.0,20.0,47.0,0.0,80.0
1431,West Virginia,2020,1789798,82.0,4.581523,5.0,1.0,0.0,2.0,0.0,...,0.0,0.0,3.0,1.0,0.0,14.0,0.0,20.0,0.0,4.0
1432,Wisconsin,2020,5892323,157.0,2.664484,3.0,1.0,3.0,0.0,0.0,...,1.0,5.0,1.0,0.0,0.0,6.0,2.0,50.0,0.0,16.0
1433,Wyoming,2020,577267,18.0,3.118141,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0

In [99]:
per_capita.to_csv('per_capita_master.csv', index=False)

In [100]:
grouped_df.to_csv('totals_with_pop_state_and_year.csv', index=False)